//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestTools.WorkItemMigrator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestTools.WorkItemMigrator.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cancel.
        /// </summary>
        internal static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string CancelWizard_MessageTitle {
            get {
                return ResourceManager.GetString("CancelWizard_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel sheet&apos;s row which is having field names for excel work items..
        /// </summary>
        internal static string CLISwitch_ExcelRow {
            get {
                return ResourceManager.GetString("CLISwitch_ExcelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file containing column and data mappings and miscellaneous settings..
        /// </summary>
        internal static string CLISwitch_InputSettings {
            get {
                return ResourceManager.GetString("CLISwitch_InputSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project at server having tcm work items..
        /// </summary>
        internal static string CLISwitch_Project {
            get {
                return ResourceManager.GetString("CLISwitch_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path of report file that will contain details of work items after the migration of work items from excel to TFS server..
        /// </summary>
        internal static string CLISwitch_ResultFile {
            get {
                return ResourceManager.GetString("CLISwitch_ResultFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination tfs server where work items have to be migrated..
        /// </summary>
        internal static string CLISwitch_Server {
            get {
                return ResourceManager.GetString("CLISwitch_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source file path.
        /// </summary>
        internal static string CLISwitch_SourceFile {
            get {
                return ResourceManager.GetString("CLISwitch_SourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Test Case Migrator Plus in UI Mode with specified settings.
        /// </summary>
        internal static string CLISwitch_UI {
            get {
                return ResourceManager.GetString("CLISwitch_UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Item type at TFS server..
        /// </summary>
        internal static string CLISwitch_WorkItemType {
            get {
                return ResourceManager.GetString("CLISwitch_WorkItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The excel worksheet having excel work items..
        /// </summary>
        internal static string CLISwitch_WorkSheetName {
            get {
                return ResourceManager.GetString("CLISwitch_WorkSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        internal static string CloseButtonLabel {
            get {
                return ResourceManager.GetString("CloseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop the migration?.
        /// </summary>
        internal static string CloseMigration_MessageTitle {
            get {
                return ResourceManager.GetString("CloseMigration_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Field Mapping.
        /// </summary>
        internal static string ColumnMappingPart_CantShowTitle {
            get {
                return ResourceManager.GetString("ColumnMappingPart_CantShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Line Usage:-.
        /// </summary>
        internal static string CommandLineUsageMessageTitle {
            get {
                return ResourceManager.GetString("CommandLineUsageMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the choices made in wizard and click &apos;Save and exit&apos; to save the settings file and exit or click &apos;Save and migrate&apos; to start the migration..
        /// </summary>
        internal static string ConfirmSettings_Description {
            get {
                return ResourceManager.GetString("ConfirmSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string ConfirmSettings_Header {
            get {
                return ResourceManager.GetString("ConfirmSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Field.
        /// </summary>
        internal static string DataMapping_DataSourceFieldHeader {
            get {
                return ResourceManager.GetString("DataMapping_DataSourceFieldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source Value.
        /// </summary>
        internal static string DataMapping_DataSourceValueHeader {
            get {
                return ResourceManager.GetString("DataMapping_DataSourceValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Value.
        /// </summary>
        internal static string Datamapping_NewValueHeader {
            get {
                return ResourceManager.GetString("Datamapping_NewValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No field names are found in provided data source information..
        /// </summary>
        internal static string DataSourceFieldNamesNotFoundErrorLikelyCause {
            get {
                return ResourceManager.GetString("DataSourceFieldNamesNotFoundErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide correct data source Information in &apos;Source&apos; which contains field names..
        /// </summary>
        internal static string DataSourceFieldNamesNotFoundErrorPotentialSolution {
            get {
                return ResourceManager.GetString("DataSourceFieldNamesNotFoundErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the data source.
        /// </summary>
        internal static string DataSourceInitializationError {
            get {
                return ResourceManager.GetString("DataSourceInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data source file.
        /// </summary>
        internal static string DataSourceInvalidFile {
            get {
                return ResourceManager.GetString("DataSourceInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data source file is either empty or the format is incorrect..
        /// </summary>
        internal static string DataSourceInvalidFileLikelyCause {
            get {
                return ResourceManager.GetString("DataSourceInvalidFileLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the correct data source file..
        /// </summary>
        internal static string DataSourceInvalidFilePotentialSolution {
            get {
                return ResourceManager.GetString("DataSourceInvalidFilePotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid excel header row .
        /// </summary>
        internal static string DataSourceInvalidHeaderInfo {
            get {
                return ResourceManager.GetString("DataSourceInvalidHeaderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel header row is not a valid number..
        /// </summary>
        internal static string DataSourceInvalidHeaderInfoLikelyCause {
            get {
                return ResourceManager.GetString("DataSourceInvalidHeaderInfoLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel header should be a positive number..
        /// </summary>
        internal static string DataSourceInvalidHeaderInfoPotentialSolution {
            get {
                return ResourceManager.GetString("DataSourceInvalidHeaderInfoPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source storage information is not provided..
        /// </summary>
        internal static string DataSourceNotEnteredErrorLikelyCause {
            get {
                return ResourceManager.GetString("DataSourceNotEnteredErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide data source file and storage information in &apos;Source&apos; wizard page..
        /// </summary>
        internal static string DataSourceNotEnteredErrorPotentialSolution {
            get {
                return ResourceManager.GetString("DataSourceNotEnteredErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid output {0} file path.
        /// </summary>
        internal static string DataSourceReportFileValidationErrorTitle {
            get {
                return ResourceManager.GetString("DataSourceReportFileValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the excel data source.
        /// </summary>
        internal static string ExcelDataSource_InitializationErrorTitle {
            get {
                return ResourceManager.GetString("ExcelDataSource_InitializationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load excel file.
        /// </summary>
        internal static string ExcelLoadError {
            get {
                return ResourceManager.GetString("ExcelLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Ignore&gt;.
        /// </summary>
        internal static string IgnoreLabel {
            get {
                return ResourceManager.GetString("IgnoreLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings file.
        /// </summary>
        internal static string InputSettingsFileError {
            get {
                return ResourceManager.GetString("InputSettingsFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings file is either not specified or invalid..
        /// </summary>
        internal static string InputSettingsFileErrorLikelyCause {
            get {
                return ResourceManager.GetString("InputSettingsFileErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that the specified file is a valid settings file generated by Test Case Migrator Plus..
        /// </summary>
        internal static string InputSettingsFileErrorPotentialSolution {
            get {
                return ResourceManager.GetString("InputSettingsFileErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have missed mapping for one or more mandatory field..
        /// </summary>
        internal static string MandatoryFieldsNotMappedErrorLikelyCause {
            get {
                return ResourceManager.GetString("MandatoryFieldsNotMappedErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that all mandatory fields are mapped..
        /// </summary>
        internal static string MandatoryFieldsNotMappedErrorPotentialSolution {
            get {
                return ResourceManager.GetString("MandatoryFieldsNotMappedErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All mandatory fields are not mapped.
        /// </summary>
        internal static string MandatoryFieldsNotMappedErrorTitle {
            get {
                return ResourceManager.GetString("MandatoryFieldsNotMappedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define the field mappings from the source fields to the TFS work item fields..
        /// </summary>
        internal static string MapColumns_Description {
            get {
                return ResourceManager.GetString("MapColumns_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field mapping.
        /// </summary>
        internal static string MapColumns_Header {
            get {
                return ResourceManager.GetString("MapColumns_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an existing settings file (containing fields mapping, data mapping, links mapping, automation scripts mapping and miscellaneous settings) or create a new settings file..
        /// </summary>
        internal static string MappingsFile_Description {
            get {
                return ResourceManager.GetString("MappingsFile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MappingsFile_Header {
            get {
                return ResourceManager.GetString("MappingsFile_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fields require you to map the data from data source to the allowed values for the destination work item field..
        /// </summary>
        internal static string MapValues_Description {
            get {
                return ResourceManager.GetString("MapValues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data mapping.
        /// </summary>
        internal static string MapValues_Header {
            get {
                return ResourceManager.GetString("MapValues_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:-
        ///
        ///Title: {0}
        ///LikelyCause: {1}
        ///PotentialSolution: {2}.
        /// </summary>
        internal static string MessageFormat {
            get {
                return ResourceManager.GetString("MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Work Items.
        /// </summary>
        internal static string MigrateWorkItemsAction_Description {
            get {
                return ResourceManager.GetString("MigrateWorkItemsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to migrate any work item. Click on error counter for more details.
        /// </summary>
        internal static string MigrateWorkItemsAction_FailedText {
            get {
                return ResourceManager.GetString("MigrateWorkItemsAction_FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} is processed.
        /// </summary>
        internal static string MigrateWorkItemsAction_InProgressText {
            get {
                return ResourceManager.GetString("MigrateWorkItemsAction_InProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the work items are not able to migrate completely. Click on Error/Warning counter for more details.
        /// </summary>
        internal static string MigrateWorkItemsAction_WarningText {
            get {
                return ResourceManager.GetString("MigrateWorkItemsAction_WarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The migration is in progress.
        /// </summary>
        internal static string MigrationInProgressText {
            get {
                return ResourceManager.GetString("MigrationInProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate.
        /// </summary>
        internal static string MigrationProgress_Header {
            get {
                return ResourceManager.GetString("MigrationProgress_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The work items were successfully migrated to TFS..
        /// </summary>
        internal static string MigrationSuccessfulText {
            get {
                return ResourceManager.GetString("MigrationSuccessfulText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify how data needs to be read from Source (Excel file) and migrated into the destination (TFS Server)..
        /// </summary>
        internal static string MiscSettings_ExcelFlow_Description {
            get {
                return ResourceManager.GetString("MiscSettings_ExcelFlow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        internal static string MiscSettings_Header {
            get {
                return ResourceManager.GetString("MiscSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file name is found in {0}.
        /// </summary>
        internal static string MiscSettings_InvalidFilePathErrorLikelyCause {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidFilePathErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify correct file name..
        /// </summary>
        internal static string MiscSettings_InvalidFilePathErrorPotentialSolution {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidFilePathErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Path: {0}.
        /// </summary>
        internal static string MiscSettings_InvalidFilePathErrorTitle {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidFilePathErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Report File Extension.
        /// </summary>
        internal static string MiscSettings_InvalidReportFileExtension {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidReportFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report file is not having Excel extension..
        /// </summary>
        internal static string MiscSettings_InvalidReportFileExtensionLikelyCause {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidReportFileExtensionLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify correct Excel extension..
        /// </summary>
        internal static string MiscSettings_InvalidReportFileExtensionPotentialSolution {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidReportFileExtensionPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Output Settings File Extension.
        /// </summary>
        internal static string MiscSettings_InvalidSettingsFileExtension {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidSettingsFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output settings file is not having xml extension..
        /// </summary>
        internal static string MiscSettings_InvalidSettingsFileExtensionLikelyCause {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidSettingsFileExtensionLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify correct xml extension..
        /// </summary>
        internal static string MiscSettings_InvalidSettingsFileExtensionPotentialSolution {
            get {
                return ResourceManager.GetString("MiscSettings_InvalidSettingsFileExtensionPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Miscellaneous Settings.
        /// </summary>
        internal static string MiscSettingsPart_CantShowTitle {
            get {
                return ResourceManager.GetString("MiscSettingsPart_CantShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _No.
        /// </summary>
        internal static string NoButtonLabel {
            get {
                return ResourceManager.GetString("NoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OK.
        /// </summary>
        internal static string OKButtonLabel {
            get {
                return ResourceManager.GetString("OKButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output settings file&apos;s name is not in correct format.
        /// </summary>
        internal static string OutputXMLFileValidationErrorLikelyCause {
            get {
                return ResourceManager.GetString("OutputXMLFileValidationErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that output settings file is valid xml file name..
        /// </summary>
        internal static string OutputXMLFileValidationErrorPotentialSolution {
            get {
                return ResourceManager.GetString("OutputXMLFileValidationErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output settings file validation error.
        /// </summary>
        internal static string OutputXMLFileValidationErrorTitle {
            get {
                return ResourceManager.GetString("OutputXMLFileValidationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Data Source.
        /// </summary>
        internal static string ParseDataSourceAction_Description {
            get {
                return ResourceManager.GetString("ParseDataSourceAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to preview file: {0}.
        /// </summary>
        internal static string PreviewDataSourceError {
            get {
                return ResourceManager.GetString("PreviewDataSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Report.
        /// </summary>
        internal static string PublishReportAction_Description {
            get {
                return ResourceManager.GetString("PublishReportAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to publish the report.
        /// </summary>
        internal static string PublisReportError {
            get {
                return ResourceManager.GetString("PublisReportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string SaveSettingsAction_Description {
            get {
                return ResourceManager.GetString("SaveSettingsAction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the source from which to migrate work item information..
        /// </summary>
        internal static string SelectDataSource_Description {
            get {
                return ResourceManager.GetString("SelectDataSource_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SelectDataSource_Header {
            get {
                return ResourceManager.GetString("SelectDataSource_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the Team Foundation Server and Team Project where you want to create the work items..
        /// </summary>
        internal static string SelectDestinationServer_Description {
            get {
                return ResourceManager.GetString("SelectDestinationServer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        internal static string SelectDestinationServer_Header {
            get {
                return ResourceManager.GetString("SelectDestinationServer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Select any value --.
        /// </summary>
        internal static string SelectPlaceholder {
            get {
                return ResourceManager.GetString("SelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Server and Project.
        /// </summary>
        internal static string SelectServerProject {
            get {
                return ResourceManager.GetString("SelectServerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;...&quot; to select Server/Project....
        /// </summary>
        internal static string SelectServerWatermarkText {
            get {
                return ResourceManager.GetString("SelectServerWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to team foundation server..
        /// </summary>
        internal static string ServerConnectionError {
            get {
                return ResourceManager.GetString("ServerConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team foundation server/Team Project Collection is not mentioned..
        /// </summary>
        internal static string ServerNotSpecifiedErrorLikelyCause {
            get {
                return ResourceManager.GetString("ServerNotSpecifiedErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify appropriate Team foundation server/Team Project Collection..
        /// </summary>
        internal static string ServerNotSpecifiedErrorPotentialSolution {
            get {
                return ResourceManager.GetString("ServerNotSpecifiedErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server connection could not be established.
        /// </summary>
        internal static string ServerNotSpecifiedErrorTitle {
            get {
                return ResourceManager.GetString("ServerNotSpecifiedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Settings File.
        /// </summary>
        internal static string SettingsFilePart_CantShowTitle {
            get {
                return ResourceManager.GetString("SettingsFilePart_CantShowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Result of the Test Step.
        /// </summary>
        internal static string TestStepExpectedResultField_HelpText {
            get {
                return ResourceManager.GetString("TestStepExpectedResultField_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of the Test Step.
        /// </summary>
        internal static string TestStepTitleField_HelpText {
            get {
                return ResourceManager.GetString("TestStepTitleField_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupted By user.
        /// </summary>
        internal static string UserInterruptionText {
            get {
                return ResourceManager.GetString("UserInterruptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName: {0} is ignored in data mapping for value: {1}; So taken the default Value: {2}
        ///.
        /// </summary>
        internal static string WarningDataSourceWorkitem_DataMappingIgnoredWarning {
            get {
                return ResourceManager.GetString("WarningDataSourceWorkitem_DataMappingIgnoredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FieldName: {0} has no value so taken the default Value: {1}
        ///.
        /// </summary>
        internal static string WarningDataSourceWorkItem_EmptyValueWarning {
            get {
                return ResourceManager.GetString("WarningDataSourceWorkItem_EmptyValueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string WelcomePageHeader {
            get {
                return ResourceManager.GetString("WelcomePageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error.
        /// </summary>
        internal static string WizardInitializationError {
            get {
                return ResourceManager.GetString("WizardInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in initializing the excel..
        /// </summary>
        internal static string WizardInitializationErrorLikelyCause {
            get {
                return ResourceManager.GetString("WizardInitializationErrorLikelyCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify that Microsoft Excel is installed in your system..
        /// </summary>
        internal static string WizardInitializationErrorPotentialSolution {
            get {
                return ResourceManager.GetString("WizardInitializationErrorPotentialSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create work items at TFS server.
        /// </summary>
        internal static string WorkItemCreationError {
            get {
                return ResourceManager.GetString("WorkItemCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Yes.
        /// </summary>
        internal static string YesButtonLabel {
            get {
                return ResourceManager.GetString("YesButtonLabel", resourceCulture);
            }
        }
    }
}
